// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA8cVb18_L0dnhN2el_Jc2dAaDstitP5XA',
    appId: '1:816028165909:web:409ec12b5bbacb570aab1c',
    messagingSenderId: '816028165909',
    projectId: 'chatapp-e0110',
    authDomain: 'chatapp-e0110.firebaseapp.com',
    storageBucket: 'chatapp-e0110.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBSChCnNxiccr0CmZTZH0A7od-EN6HnnfY',
    appId: '1:816028165909:android:034d022a4369dcd60aab1c',
    messagingSenderId: '816028165909',
    projectId: 'chatapp-e0110',
    storageBucket: 'chatapp-e0110.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyChOFm-4Wdu_mO67xoeK1UmbhsT9pCQoh0',
    appId: '1:816028165909:ios:81e3bda7b43c9a430aab1c',
    messagingSenderId: '816028165909',
    projectId: 'chatapp-e0110',
    storageBucket: 'chatapp-e0110.appspot.com',
    iosBundleId: 'com.example.chatapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyChOFm-4Wdu_mO67xoeK1UmbhsT9pCQoh0',
    appId: '1:816028165909:ios:06fa71e1c5e825000aab1c',
    messagingSenderId: '816028165909',
    projectId: 'chatapp-e0110',
    storageBucket: 'chatapp-e0110.appspot.com',
    iosBundleId: 'com.example.chatapp.RunnerTests',
  );
}
